### ISSUE TITLE
语音似乎失效了

### ISSUE THREAD

**Issue by macoswk** [akl7777777/bob-plugin-akl-microsoft-free-tts#9]
<img width="367" alt="截屏2023-12-20 上午9 53 53" src="https://github.com/akl7777777/bob-plugin-akl-microsoft-free-tts/assets/86730293/5d0b044d-276c-4a8c-bf26-0722a4616510">

**Comment by ZwxwZ** [comment]
一样

**Comment by ryanwuson** [comment]
一样

**Comment by abbzbb** [comment]
Yes, it didn't work!

**Comment by qianzhongzhong** [comment]
作者摆烂了
